on:
  push:
  pull_request:
    types: [opened, closed]

jobs:
  notify:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Notify github action on Telegram
      uses: EverythingSuckz/github-telegram-notify@main
      with:
        bot_token: '${{ secrets.TELEGRAM_TOKEN }}'
        chat_id: '${{ secrets.TELEGRAM_TO }}'

  notify2:
    name: Build
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify github action on Telegram
        uses: EverythingSuckz/github-telegram-notify@main
        with:
          bot_token: '${{ secrets.TELEGRAM_TOKEN }}'
          chat_id: '${{ secrets.TELEGRAM_TO }}'